spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_hw
    username: postgres
    password: root
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
#  sql:
#    init:
#      mode: always
